repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff-lint
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
        name: ruff-format

  - repo: local
    hooks:
      - id: pyrefly-check
        name: pyrefly-check
        entry: uv run pyrefly check
        language: system
        types: [python]
        pass_filenames: false
