"""Add catalog models

Revision ID: df9847a07952
Revises:
Create Date: 2026-01-25 04:52:13.757601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df9847a07952"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="로그 ID"),
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("action", sa.String(length=50), nullable=False, comment="액션"),
        sa.Column("target", sa.String(length=255), nullable=False, comment="대상 (토픽명)"),
        sa.Column("team", sa.String(length=100), nullable=True, comment="팀 (토픽 소유자)"),
        sa.Column("actor", sa.String(length=100), nullable=False, comment="수행자"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="상태"),
        sa.Column("message", sa.Text(), nullable=True, comment="메시지"),
        sa.Column("snapshot", sa.JSON(), nullable=True, comment="스냅샷 (JSON)"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="로그 시간",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "consumer_group_rebalance_delta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="델타 ID"),
        sa.Column("cluster_id", sa.String(length=255), nullable=False, comment="클러스터 ID"),
        sa.Column("group_id", sa.String(length=255), nullable=False, comment="Consumer Group ID"),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="리밸런스 발생 시각",
        ),
        sa.Column(
            "moved_partitions", sa.Integer(), nullable=False, comment="이전 대비 이동한 파티션 수"
        ),
        sa.Column("join_count", sa.Integer(), nullable=False, comment="새로 참여한 멤버 수"),
        sa.Column("leave_count", sa.Integer(), nullable=False, comment="떠난 멤버 수"),
        sa.Column(
            "elapsed_since_prev_s",
            sa.Integer(),
            nullable=True,
            comment="직전 리밸런스 이후 경과 시간 (초)",
        ),
        sa.Column("state", sa.String(length=50), nullable=False, comment="리밸런스 후 그룹 상태"),
        sa.Column(
            "assignment_hash",
            sa.String(length=40),
            nullable=False,
            comment="TP→Member 매핑의 SHA-1 해시",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer_group_rebalance_delta")),
    )
    op.create_index(
        "idx_consumer_rebalance_delta_cluster_group_ts",
        "consumer_group_rebalance_delta",
        ["cluster_id", "group_id", "ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_rebalance_delta_cluster_id"),
        "consumer_group_rebalance_delta",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_rebalance_delta_group_id"),
        "consumer_group_rebalance_delta",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_rebalance_delta_ts"),
        "consumer_group_rebalance_delta",
        ["ts"],
        unique=False,
    )
    op.create_table(
        "consumer_group_rebalance_rollup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="롤업 ID"),
        sa.Column("cluster_id", sa.String(length=255), nullable=False, comment="클러스터 ID"),
        sa.Column("group_id", sa.String(length=255), nullable=False, comment="Consumer Group ID"),
        sa.Column(
            "window_start", sa.DateTime(timezone=True), nullable=False, comment="윈도우 시작 시각"
        ),
        sa.Column(
            "window",
            sa.Enum("5m", "1h", name="rollup_window_enum"),
            nullable=False,
            comment="집계 단위 (5분/1시간)",
        ),
        sa.Column("rebalances", sa.Integer(), nullable=False, comment="윈도우 내 리밸런스 횟수"),
        sa.Column("avg_moved_partitions", sa.Float(), nullable=True, comment="평균 이동 파티션 수"),
        sa.Column(
            "max_moved_partitions", sa.Integer(), nullable=True, comment="최대 이동 파티션 수"
        ),
        sa.Column(
            "stable_ratio",
            sa.Float(),
            nullable=True,
            comment="안정 유지 비율 (stable_time / total_time)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer_group_rebalance_rollup")),
        sa.UniqueConstraint(
            "cluster_id", "group_id", "window", "window_start", name="uk_consumer_rebalance_rollup"
        ),
    )
    op.create_index(
        "idx_consumer_rebalance_rollup_cluster_group_window",
        "consumer_group_rebalance_rollup",
        ["cluster_id", "group_id", "window"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_rebalance_rollup_cluster_id"),
        "consumer_group_rebalance_rollup",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_rebalance_rollup_group_id"),
        "consumer_group_rebalance_rollup",
        ["group_id"],
        unique=False,
    )
    op.create_table(
        "consumer_group_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="스냅샷 ID"),
        sa.Column("cluster_id", sa.String(length=255), nullable=False, comment="클러스터 ID"),
        sa.Column("group_id", sa.String(length=255), nullable=False, comment="Consumer Group ID"),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수집 시각",
        ),
        sa.Column(
            "state",
            sa.String(length=50),
            nullable=False,
            comment="그룹 상태 (Stable/Rebalancing/Empty/Dead)",
        ),
        sa.Column(
            "partition_assignor",
            sa.String(length=100),
            nullable=True,
            comment="파티션 할당 알고리즘 (range/roundrobin/cooperative-sticky)",
        ),
        sa.Column("member_count", sa.Integer(), nullable=False, comment="멤버 수"),
        sa.Column("topic_count", sa.Integer(), nullable=False, comment="구독 토픽 수"),
        sa.Column("total_lag", sa.BigInteger(), nullable=False, comment="전체 lag 합"),
        sa.Column("p50_lag", sa.BigInteger(), nullable=True, comment="P50 lag (중간값)"),
        sa.Column("p95_lag", sa.BigInteger(), nullable=True, comment="P95 lag"),
        sa.Column("max_lag", sa.BigInteger(), nullable=True, comment="최대 lag"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer_group_snapshot")),
    )
    op.create_index(
        "idx_consumer_group_snapshot_cluster_group_ts",
        "consumer_group_snapshot",
        ["cluster_id", "group_id", "ts"],
        unique=False,
    )
    op.create_index(
        "idx_consumer_group_snapshot_ts", "consumer_group_snapshot", ["ts"], unique=False
    )
    op.create_index(
        op.f("ix_consumer_group_snapshot_cluster_id"),
        "consumer_group_snapshot",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_snapshot_group_id"),
        "consumer_group_snapshot",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_group_snapshot_ts"), "consumer_group_snapshot", ["ts"], unique=False
    )
    op.create_table(
        "consumer_member_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="스냅샷 ID"),
        sa.Column("cluster_id", sa.String(length=255), nullable=False, comment="클러스터 ID"),
        sa.Column("group_id", sa.String(length=255), nullable=False, comment="Consumer Group ID"),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수집 시각",
        ),
        sa.Column(
            "member_id",
            sa.String(length=255),
            nullable=False,
            comment="GroupCoordinator 부여 멤버 ID",
        ),
        sa.Column(
            "client_id", sa.String(length=255), nullable=True, comment="Consumer client 식별자"
        ),
        sa.Column("client_host", sa.String(length=255), nullable=True, comment="실행 호스트 IP"),
        sa.Column("assigned_tp_count", sa.Integer(), nullable=False, comment="담당 파티션 수"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer_member_snapshot")),
    )
    op.create_index(
        "idx_consumer_member_snapshot_cluster_group_ts",
        "consumer_member_snapshot",
        ["cluster_id", "group_id", "ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_member_snapshot_cluster_id"),
        "consumer_member_snapshot",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_member_snapshot_group_id"),
        "consumer_member_snapshot",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_member_snapshot_ts"), "consumer_member_snapshot", ["ts"], unique=False
    )
    op.create_table(
        "consumer_partition_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="스냅샷 ID"),
        sa.Column("cluster_id", sa.String(length=255), nullable=False, comment="클러스터 ID"),
        sa.Column("group_id", sa.String(length=255), nullable=False, comment="Consumer Group ID"),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수집 시각",
        ),
        sa.Column("topic", sa.String(length=255), nullable=False, comment="토픽 이름"),
        sa.Column("partition", sa.Integer(), nullable=False, comment="파티션 번호"),
        sa.Column(
            "committed_offset",
            sa.BigInteger(),
            nullable=True,
            comment="그룹의 커밋 오프셋 (list_consumer_group_offsets)",
        ),
        sa.Column(
            "latest_offset",
            sa.BigInteger(),
            nullable=True,
            comment="브로커 최신 오프셋 (list_offsets)",
        ),
        sa.Column(
            "lag", sa.BigInteger(), nullable=True, comment="Lag (latest_offset - committed_offset)"
        ),
        sa.Column(
            "assigned_member_id",
            sa.String(length=255),
            nullable=True,
            comment="담당 consumer 멤버 ID",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer_partition_snapshot")),
    )
    op.create_index(
        "idx_consumer_partition_snapshot_cluster_group_ts",
        "consumer_partition_snapshot",
        ["cluster_id", "group_id", "ts"],
        unique=False,
    )
    op.create_index(
        "idx_consumer_partition_snapshot_cluster_topic_ts",
        "consumer_partition_snapshot",
        ["cluster_id", "topic", "ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_partition_snapshot_cluster_id"),
        "consumer_partition_snapshot",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_partition_snapshot_group_id"),
        "consumer_partition_snapshot",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_partition_snapshot_topic"),
        "consumer_partition_snapshot",
        ["topic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_partition_snapshot_ts"),
        "consumer_partition_snapshot",
        ["ts"],
        unique=False,
    )
    op.create_table(
        "kafka_clusters",
        sa.Column("cluster_id", sa.String(length=100), nullable=False, comment="클러스터 ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="클러스터 이름"),
        sa.Column("bootstrap_servers", sa.Text(), nullable=False, comment="브로커 주소"),
        sa.Column("description", sa.Text(), nullable=True, comment="설명"),
        sa.Column(
            "security_protocol", sa.String(length=50), nullable=False, comment="보안 프로토콜"
        ),
        sa.Column("sasl_mechanism", sa.String(length=50), nullable=True, comment="SASL 메커니즘"),
        sa.Column("sasl_username", sa.String(length=255), nullable=True, comment="SASL 사용자명"),
        sa.Column(
            "sasl_password", sa.String(length=255), nullable=True, comment="SASL 비밀번호 (암호화)"
        ),
        sa.Column(
            "ssl_ca_location", sa.String(length=500), nullable=True, comment="SSL CA 인증서 경로"
        ),
        sa.Column(
            "ssl_cert_location", sa.String(length=500), nullable=True, comment="SSL 인증서 경로"
        ),
        sa.Column("ssl_key_location", sa.String(length=500), nullable=True, comment="SSL 키 경로"),
        sa.Column("request_timeout_ms", sa.Integer(), nullable=False, comment="요청 타임아웃(ms)"),
        sa.Column("socket_timeout_ms", sa.Integer(), nullable=False, comment="소켓 타임아웃(ms)"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="활성화 여부"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수정 시간",
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_kafka_clusters")),
    )
    op.create_table(
        "metrics_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", sa.String(length=100), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("broker_count", sa.Integer(), nullable=False),
        sa.Column("total_partitions", sa.Integer(), nullable=False),
        sa.Column("partition_to_broker_ratio", sa.Float(), nullable=False),
        sa.Column("log_dir", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics_snapshots")),
    )
    op.create_index(
        "idx_cluster_collected", "metrics_snapshots", ["cluster_id", "collected_at"], unique=False
    )
    op.create_index(
        "idx_collected_at_desc",
        "metrics_snapshots",
        ["collected_at"],
        unique=False,
        postgresql_ops={"collected_at": "DESC"},
    )
    op.create_index(
        op.f("ix_metrics_snapshots_cluster_id"), "metrics_snapshots", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_metrics_snapshots_collected_at"),
        "metrics_snapshots",
        ["collected_at"],
        unique=False,
    )
    op.create_table(
        "observed_usage",
        sa.Column("subject", sa.String(length=512), nullable=False, comment="Subject 이름"),
        sa.Column("version", sa.Integer(), nullable=False, comment="버전 번호"),
        sa.Column("topics", sa.JSON(), nullable=True, comment="사용 중인 토픽 목록"),
        sa.Column("consumers", sa.JSON(), nullable=True, comment="사용 중인 컨슈머 그룹 목록"),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="최근 관측 시간",
        ),
        sa.PrimaryKeyConstraint("subject", "version", name=op.f("pk_observed_usage")),
    )
    op.create_index("idx_last_seen", "observed_usage", ["last_seen_at"], unique=False)
    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="레코드 ID"),
        sa.Column("policy_id", sa.String(length=36), nullable=False, comment="정책 UUID"),
        sa.Column("version", sa.Integer(), nullable=False, comment="버전 번호 (1, 2, 3...)"),
        sa.Column(
            "policy_type",
            sa.Enum("naming", "guardrail", name="policy_type_enum"),
            nullable=False,
            comment="정책 타입",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="정책 이름"),
        sa.Column("description", sa.Text(), nullable=False, comment="정책 설명"),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="policy_status_enum"),
            nullable=False,
            comment="정책 상태",
        ),
        sa.Column("content", sa.JSON(), nullable=False, comment="정책 내용 (JSON)"),
        sa.Column(
            "target_environment",
            sa.String(length=20),
            server_default="total",
            nullable=False,
            comment="적용 환경",
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False, comment="생성자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="수정 시간"),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="활성화 시간 (ACTIVE 상태가 된 시점)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint("policy_id", "version", name="uq_policy_version"),
        comment="정책 버전 관리 테이블",
    )
    op.create_table(
        "schema_apply_results",
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("result_data", sa.JSON(), nullable=False, comment="적용 결과 (JSON)"),
        sa.Column("registered_count", sa.Integer(), nullable=False, comment="등록 성공 개수"),
        sa.Column("failed_count", sa.Integer(), nullable=False, comment="실패 개수"),
        sa.Column("applied_by", sa.String(length=100), nullable=False, comment="적용자"),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="적용 시간",
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_schema_apply_results")),
    )
    op.create_table(
        "schema_artifacts",
        sa.Column("subject", sa.String(length=255), nullable=False, comment="Subject 이름"),
        sa.Column("version", sa.Integer(), nullable=False, comment="스키마 버전"),
        sa.Column("storage_url", sa.Text(), nullable=True, comment="저장소 URL (optional)"),
        sa.Column("checksum", sa.String(length=64), nullable=True, comment="체크섬"),
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("schema_type", sa.String(length=20), nullable=False, comment="스키마 타입"),
        sa.Column("file_size", sa.Integer(), nullable=True, comment="파일 크기 (bytes)"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.PrimaryKeyConstraint("subject", "version", name=op.f("pk_schema_artifacts")),
    )
    op.create_table(
        "schema_audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="로그 ID"),
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("action", sa.String(length=50), nullable=False, comment="액션"),
        sa.Column("target", sa.String(length=255), nullable=False, comment="대상 (Subject명)"),
        sa.Column("actor", sa.String(length=100), nullable=False, comment="수행자"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="상태"),
        sa.Column("message", sa.Text(), nullable=True, comment="메시지"),
        sa.Column("snapshot", sa.JSON(), nullable=True, comment="스냅샷 (JSON)"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="로그 시간",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_audit_logs")),
    )
    op.create_table(
        "schema_metadata",
        sa.Column("subject", sa.String(length=255), nullable=False, comment="Subject 이름"),
        sa.Column("owner", sa.String(length=100), nullable=True, comment="소유자"),
        sa.Column("doc", sa.Text(), nullable=True, comment="문서/설명"),
        sa.Column("tags", sa.JSON(), nullable=True, comment="태그 (JSON)"),
        sa.Column("description", sa.Text(), nullable=True, comment="스키마 설명"),
        sa.Column("created_by", sa.String(length=100), nullable=False, comment="생성자"),
        sa.Column("updated_by", sa.String(length=100), nullable=False, comment="수정자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수정 시간",
        ),
        sa.PrimaryKeyConstraint("subject", name=op.f("pk_schema_metadata")),
    )
    op.create_table(
        "schema_plans",
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("env", sa.String(length=50), nullable=False, comment="환경 (dev/stg/prod)"),
        sa.Column("plan_data", sa.JSON(), nullable=False, comment="계획 데이터 (JSON)"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="상태"),
        sa.Column("can_apply", sa.Boolean(), nullable=False, comment="적용 가능 여부"),
        sa.Column("created_by", sa.String(length=100), nullable=False, comment="생성자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column("updated_by", sa.String(length=100), nullable=True, comment="수정자"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="수정 시간"),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_schema_plans")),
    )
    op.create_table(
        "schema_registries",
        sa.Column("registry_id", sa.String(length=100), nullable=False, comment="레지스트리 ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="레지스트리 이름"),
        sa.Column("url", sa.Text(), nullable=False, comment="레지스트리 URL"),
        sa.Column("description", sa.Text(), nullable=True, comment="설명"),
        sa.Column("auth_username", sa.String(length=255), nullable=True, comment="인증 사용자명"),
        sa.Column(
            "auth_password", sa.String(length=255), nullable=True, comment="인증 비밀번호 (암호화)"
        ),
        sa.Column(
            "ssl_ca_location", sa.String(length=500), nullable=True, comment="SSL CA 인증서 경로"
        ),
        sa.Column(
            "ssl_cert_location", sa.String(length=500), nullable=True, comment="SSL 인증서 경로"
        ),
        sa.Column("ssl_key_location", sa.String(length=500), nullable=True, comment="SSL 키 경로"),
        sa.Column("timeout", sa.Integer(), nullable=False, comment="요청 타임아웃(초)"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="활성화 여부"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수정 시간",
        ),
        sa.PrimaryKeyConstraint("registry_id", name=op.f("pk_schema_registries")),
    )
    op.create_table(
        "schema_subjects",
        sa.Column("subject", sa.String(length=512), nullable=False, comment="Subject 이름"),
        sa.Column("latest_version", sa.Integer(), nullable=True, comment="최신 버전 번호"),
        sa.Column(
            "compat_level",
            sa.String(length=50),
            nullable=True,
            comment="호환성 레벨 (BACKWARD, FORWARD 등)",
        ),
        sa.Column("mode_readonly", sa.Boolean(), nullable=False, comment="READONLY 모드 여부"),
        sa.Column(
            "env",
            sa.String(length=20),
            nullable=True,
            comment="환경 (dev/stg/prod) - subject명에서 추출",
        ),
        sa.Column(
            "owner_team",
            sa.String(length=100),
            nullable=True,
            comment="소유 팀 - naming에서 추출 또는 수동 태깅",
        ),
        sa.Column("pii_score", sa.Float(), nullable=False, comment="PII 가능성 점수 (0.0~1.0)"),
        sa.Column(
            "risk_score",
            sa.Float(),
            nullable=False,
            comment="리스크 점수 (0.0~1.0) - lint+drift 가중",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="최종 동기화 시간",
        ),
        sa.PrimaryKeyConstraint("subject", name=op.f("pk_schema_subjects")),
    )
    op.create_index("idx_env_team", "schema_subjects", ["env", "owner_team"], unique=False)
    op.create_index("idx_risk_score", "schema_subjects", ["risk_score"], unique=False)
    op.create_table(
        "schema_upload_results",
        sa.Column("upload_id", sa.String(length=100), nullable=False, comment="업로드 ID"),
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("artifacts", sa.JSON(), nullable=False, comment="업로드된 아티팩트 목록 (JSON)"),
        sa.Column("artifact_count", sa.Integer(), nullable=False, comment="아티팩트 개수"),
        sa.Column("uploaded_by", sa.String(length=100), nullable=False, comment="업로드한 사용자"),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="업로드 시간",
        ),
        sa.PrimaryKeyConstraint("upload_id", name=op.f("pk_schema_upload_results")),
    )
    op.create_table(
        "schema_versions",
        sa.Column("subject", sa.String(length=512), nullable=False, comment="Subject 이름"),
        sa.Column("version", sa.Integer(), nullable=False, comment="버전 번호"),
        sa.Column(
            "schema_type",
            sa.String(length=50),
            nullable=False,
            comment="스키마 타입 (AVRO, JSON, PROTOBUF)",
        ),
        sa.Column("schema_id", sa.Integer(), nullable=True, comment="SR 스키마 ID"),
        sa.Column("schema_str", sa.Text(), nullable=False, comment="스키마 본문 (원본)"),
        sa.Column(
            "schema_canonical_hash",
            sa.String(length=64),
            nullable=True,
            comment="정규화 후 SHA-256 해시",
        ),
        sa.Column(
            "references",
            sa.JSON(),
            nullable=True,
            comment="스키마 참조 (Schema Registry references)",
        ),
        sa.Column(
            "rule_set", sa.JSON(), nullable=True, comment="SR Rule Set (migration, domain rules)"
        ),
        sa.Column(
            "sr_metadata",
            sa.JSON(),
            nullable=True,
            comment="SR Metadata properties (tags, sensitive 등)",
        ),
        sa.Column(
            "fields_meta",
            sa.JSON(),
            nullable=True,
            comment="필드별 메타 (타입, PII 후보, 네이밍 등)",
        ),
        sa.Column(
            "lint_report",
            sa.JSON(),
            nullable=True,
            comment="Lint 리포트 (violations: [{code, severity, rule, hint}])",
        ),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="SR 등록 시간 (또는 첫 수집 시간)",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="마지막 동기화 시간",
        ),
        sa.PrimaryKeyConstraint("subject", "version", name=op.f("pk_schema_versions")),
    )
    op.create_index(
        "idx_canonical_hash", "schema_versions", ["schema_canonical_hash"], unique=False
    )
    op.create_index("idx_schema_type", "schema_versions", ["schema_type"], unique=False)
    op.create_index("idx_subject_version", "schema_versions", ["subject", "version"], unique=False)
    op.create_table(
        "topic_apply_results",
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("result_data", sa.JSON(), nullable=False, comment="적용 결과 (JSON)"),
        sa.Column("success_count", sa.Integer(), nullable=False, comment="성공 개수"),
        sa.Column("failure_count", sa.Integer(), nullable=False, comment="실패 개수"),
        sa.Column("applied_by", sa.String(length=100), nullable=False, comment="적용자"),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="적용 시간",
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_topic_apply_results")),
    )
    op.create_table(
        "topic_metadata",
        sa.Column("topic_name", sa.String(length=255), nullable=False, comment="토픽 이름"),
        sa.Column("owners", sa.JSON(), nullable=True, comment="소유자 목록 (JSON 배열)"),
        sa.Column("doc", sa.Text(), nullable=True, comment="문서/설명"),
        sa.Column("tags", sa.JSON(), nullable=True, comment="태그 (JSON)"),
        sa.Column(
            "environment", sa.String(length=20), nullable=True, comment="환경 (dev/stg/prod)"
        ),
        sa.Column("slo", sa.Text(), nullable=True, comment="SLO (Service Level Objective)"),
        sa.Column("sla", sa.Text(), nullable=True, comment="SLA (Service Level Agreement)"),
        sa.Column("config", sa.JSON(), nullable=True, comment="토픽 설정"),
        sa.Column("created_by", sa.String(length=100), nullable=False, comment="생성자"),
        sa.Column("updated_by", sa.String(length=100), nullable=False, comment="수정자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="수정 시간",
        ),
        sa.PrimaryKeyConstraint("topic_name", name=op.f("pk_topic_metadata")),
    )
    op.create_table(
        "topic_plans",
        sa.Column("change_id", sa.String(length=100), nullable=False, comment="변경 ID"),
        sa.Column("env", sa.String(length=50), nullable=False, comment="환경 (dev/staging/prod)"),
        sa.Column("plan_data", sa.JSON(), nullable=False, comment="계획 데이터 (JSON)"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="상태"),
        sa.Column("can_apply", sa.Boolean(), nullable=False, comment="적용 가능 여부"),
        sa.Column("created_by", sa.String(length=100), nullable=False, comment="생성자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="생성 시간",
        ),
        sa.Column("updated_by", sa.String(length=100), nullable=True, comment="수정자"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="수정 시간"),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_topic_plans")),
    )
    op.create_table(
        "leader_distributions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column("leader_partition_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["metrics_snapshots.id"],
            name=op.f("fk_leader_distributions_snapshot_id_metrics_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leader_distributions")),
    )
    op.create_index(
        "idx_snapshot_broker", "leader_distributions", ["snapshot_id", "broker_id"], unique=False
    )
    op.create_index(
        op.f("ix_leader_distributions_snapshot_id"),
        "leader_distributions",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "topic_partition_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("topic_name", sa.String(length=255), nullable=False),
        sa.Column("partition_count", sa.Integer(), nullable=False),
        sa.Column("total_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("avg_partition_size", sa.BigInteger(), nullable=False),
        sa.Column("max_partition_size", sa.BigInteger(), nullable=False),
        sa.Column("min_partition_size", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["metrics_snapshots.id"],
            name=op.f("fk_topic_partition_metrics_snapshot_id_metrics_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_partition_metrics")),
    )
    op.create_index(
        "idx_snapshot_topic", "topic_partition_metrics", ["snapshot_id", "topic_name"], unique=False
    )
    op.create_index("idx_topic_name", "topic_partition_metrics", ["topic_name"], unique=False)
    op.create_index(
        op.f("ix_topic_partition_metrics_snapshot_id"),
        "topic_partition_metrics",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_partition_metrics_topic_name"),
        "topic_partition_metrics",
        ["topic_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_topic_partition_metrics_topic_name"), table_name="topic_partition_metrics"
    )
    op.drop_index(
        op.f("ix_topic_partition_metrics_snapshot_id"), table_name="topic_partition_metrics"
    )
    op.drop_index("idx_topic_name", table_name="topic_partition_metrics")
    op.drop_index("idx_snapshot_topic", table_name="topic_partition_metrics")
    op.drop_table("topic_partition_metrics")
    op.drop_index(op.f("ix_leader_distributions_snapshot_id"), table_name="leader_distributions")
    op.drop_index("idx_snapshot_broker", table_name="leader_distributions")
    op.drop_table("leader_distributions")
    op.drop_table("topic_plans")
    op.drop_table("topic_metadata")
    op.drop_table("topic_apply_results")
    op.drop_index("idx_subject_version", table_name="schema_versions")
    op.drop_index("idx_schema_type", table_name="schema_versions")
    op.drop_index("idx_canonical_hash", table_name="schema_versions")
    op.drop_table("schema_versions")
    op.drop_table("schema_upload_results")
    op.drop_index("idx_risk_score", table_name="schema_subjects")
    op.drop_index("idx_env_team", table_name="schema_subjects")
    op.drop_table("schema_subjects")
    op.drop_table("schema_registries")
    op.drop_table("schema_plans")
    op.drop_table("schema_metadata")
    op.drop_table("schema_audit_logs")
    op.drop_table("schema_artifacts")
    op.drop_table("schema_apply_results")
    op.drop_table("policies")
    op.drop_index("idx_last_seen", table_name="observed_usage")
    op.drop_table("observed_usage")
    op.drop_index(op.f("ix_metrics_snapshots_collected_at"), table_name="metrics_snapshots")
    op.drop_index(op.f("ix_metrics_snapshots_cluster_id"), table_name="metrics_snapshots")
    op.drop_index(
        "idx_collected_at_desc",
        table_name="metrics_snapshots",
        postgresql_ops={"collected_at": "DESC"},
    )
    op.drop_index("idx_cluster_collected", table_name="metrics_snapshots")
    op.drop_table("metrics_snapshots")
    op.drop_table("kafka_clusters")
    op.drop_index(
        op.f("ix_consumer_partition_snapshot_ts"), table_name="consumer_partition_snapshot"
    )
    op.drop_index(
        op.f("ix_consumer_partition_snapshot_topic"), table_name="consumer_partition_snapshot"
    )
    op.drop_index(
        op.f("ix_consumer_partition_snapshot_group_id"), table_name="consumer_partition_snapshot"
    )
    op.drop_index(
        op.f("ix_consumer_partition_snapshot_cluster_id"), table_name="consumer_partition_snapshot"
    )
    op.drop_index(
        "idx_consumer_partition_snapshot_cluster_topic_ts", table_name="consumer_partition_snapshot"
    )
    op.drop_index(
        "idx_consumer_partition_snapshot_cluster_group_ts", table_name="consumer_partition_snapshot"
    )
    op.drop_table("consumer_partition_snapshot")
    op.drop_index(op.f("ix_consumer_member_snapshot_ts"), table_name="consumer_member_snapshot")
    op.drop_index(
        op.f("ix_consumer_member_snapshot_group_id"), table_name="consumer_member_snapshot"
    )
    op.drop_index(
        op.f("ix_consumer_member_snapshot_cluster_id"), table_name="consumer_member_snapshot"
    )
    op.drop_index(
        "idx_consumer_member_snapshot_cluster_group_ts", table_name="consumer_member_snapshot"
    )
    op.drop_table("consumer_member_snapshot")
    op.drop_index(op.f("ix_consumer_group_snapshot_ts"), table_name="consumer_group_snapshot")
    op.drop_index(op.f("ix_consumer_group_snapshot_group_id"), table_name="consumer_group_snapshot")
    op.drop_index(
        op.f("ix_consumer_group_snapshot_cluster_id"), table_name="consumer_group_snapshot"
    )
    op.drop_index("idx_consumer_group_snapshot_ts", table_name="consumer_group_snapshot")
    op.drop_index(
        "idx_consumer_group_snapshot_cluster_group_ts", table_name="consumer_group_snapshot"
    )
    op.drop_table("consumer_group_snapshot")
    op.drop_index(
        op.f("ix_consumer_group_rebalance_rollup_group_id"),
        table_name="consumer_group_rebalance_rollup",
    )
    op.drop_index(
        op.f("ix_consumer_group_rebalance_rollup_cluster_id"),
        table_name="consumer_group_rebalance_rollup",
    )
    op.drop_index(
        "idx_consumer_rebalance_rollup_cluster_group_window",
        table_name="consumer_group_rebalance_rollup",
    )
    op.drop_table("consumer_group_rebalance_rollup")
    op.drop_index(
        op.f("ix_consumer_group_rebalance_delta_ts"), table_name="consumer_group_rebalance_delta"
    )
    op.drop_index(
        op.f("ix_consumer_group_rebalance_delta_group_id"),
        table_name="consumer_group_rebalance_delta",
    )
    op.drop_index(
        op.f("ix_consumer_group_rebalance_delta_cluster_id"),
        table_name="consumer_group_rebalance_delta",
    )
    op.drop_index(
        "idx_consumer_rebalance_delta_cluster_group_ts", table_name="consumer_group_rebalance_delta"
    )
    op.drop_table("consumer_group_rebalance_delta")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
