"""Topic Interface 타입 정의"""

from .enums import CleanupPolicy, CompressionType, Environment, TopicAction
from .type_hints import (
    AuditId,
    ChangeId,
    DocumentUrl,
    ErrorField,
    ErrorMessage,
    ErrorRule,
    ErrorSeverity,
    MaxMessageBytes,
    MinInsyncReplicas,
    PartitionCount,
    PlanAction,
    PlanStatus,
    ReasonText,
    ReplicationFactor,
    RetentionMs,
    SegmentMs,
    SlaRequirement,
    TagName,
    TeamName,
    TopicName,
)

__all__ = [
    "AuditId",
    "ChangeId",
    "CleanupPolicy",
    "CompressionType",
    "DocumentUrl",
    "Environment",
    "ErrorField",
    "ErrorMessage",
    "ErrorRule",
    "ErrorSeverity",
    "MaxMessageBytes",
    "MinInsyncReplicas",
    "PartitionCount",
    "PlanAction",
    "PlanStatus",
    "ReasonText",
    "ReplicationFactor",
    "RetentionMs",
    "SegmentMs",
    "SlaRequirement",
    "TagName",
    "TeamName",
    "TopicAction",
    "TopicName",
]
